def init_offers(db):
    print("Initializing offers collection...")

    offers = db["offers"]
    offers.insert_many([
        {
            "_id": 1,
            "user_id": 1,
            "vehicle_id": 1,
            "price": 12000,
            "description": "Great car, perfect for drifting",
            "status": "active",
            "color": "Red",
            "milage": 150000,
            "vin": "1HGBH41JXMN109186",
            "condition": "Used",
            "created_at": "2025-03-29 10:00:00",
            "modified_at": None
        },
        {
            "_id": 2,
            "user_id": 2,
            "vehicle_id": 3,
            "price": 15000,
            "description": "Needs some work, but it's a solid vehicle",
            "status": "inactive",
            "color": "Black",
            "milage": 120000,
            "vin": "1HGBH41JXMN109187",
            "condition": "Used",
            "created_at": "2025-03-29 10:05:00",
            "modified_at": None
        },
        {
            "_id": 3,
            "user_id": 3,
            "vehicle_id": 5,
            "price": 18000,
            "description": "Fully modified for drifting",
            "status": "active",
            "color": "White",
            "milage": 100000,
            "vin": "1HGBH41JXMN109188",
            "condition": "Excellent",
            "created_at": "2025-03-29 10:10:00",
            "modified_at": None
        },
        {
            "_id": 4,
            "user_id": 4,
            "vehicle_id": 2,
            "price": 11000,
            "description": "Lightly modified, great for street and track",
            "status": "active",
            "color": "Blue",
            "milage": 130000,
            "vin": "1HGBH41JXMN109189",
            "condition": "Good",
            "created_at": "2025-03-29 10:15:00",
            "modified_at": None
        },
        {
            "_id": 5,
            "user_id": 5,
            "vehicle_id": 4,
            "price": 22000,
            "description": "Drift-ready, all modifications done",
            "status": "active",
            "color": "Green",
            "milage": 95000,
            "vin": "1HGBH41JXMN109190",
            "condition": "Excellent",
            "created_at": "2025-03-29 10:20:00",
            "modified_at": None
        },
        {
            "_id": 6,
            "user_id": 6,
            "vehicle_id": 6,
            "price": 10000,
            "description": "Stock condition, good for a budget build",
            "status": "inactive",
            "color": "Silver",
            "milage": 140000,
            "vin": "1HGBH41JXMN109191",
            "condition": "Fair",
            "created_at": "2025-03-29 10:25:00",
            "modified_at": None
        },
        {
            "_id": 7,
            "user_id": 7,
            "vehicle_id": 7,
            "price": 14000,
            "description": "Perfect for beginners, few mods added",
            "status": "active",
            "color": "Yellow",
            "milage": 110000,
            "vin": "1HGBH41JXMN109192",
            "condition": "Used",
            "created_at": "2025-03-29 10:30:00",
            "modified_at": None
        },
        {
            "_id": 8,
            "user_id": 8,
            "vehicle_id": 8,
            "price": 16000,
            "description": "Custom engine swap, great for drifting",
            "status": "active",
            "color": "Purple",
            "milage": 85000,
            "vin": "1HGBH41JXMN109193",
            "condition": "Excellent",
            "created_at": "2025-03-29 10:35:00",
            "modified_at": None
        },
        {
            "_id": 9,
            "user_id": 9,
            "vehicle_id": 9,
            "price": 13000,
            "description": "Old but reliable, needs some work",
            "status": "inactive",
            "color": "Orange",
            "milage": 160000,
            "vin": "1HGBH41JXMN109194",
            "condition": "Fair",
            "created_at": "2025-03-29 10:40:00",
            "modified_at": None
        },
        {
            "_id": 10,
            "user_id": 10,
            "vehicle_id": 10,
            "price": 25000,
            "description": "Rare car, amazing condition, drift ready",
            "status": "active",
            "color": "Pink",
            "milage": 90000,
            "vin": "1HGBH41JXMN109195",
            "condition": "Excellent",
            "created_at": "2025-03-29 10:45:00",
            "modified_at": None
        }
    ])